// Mocks generated by Mockito 5.3.2 from annotations
// in tvseries/test/presentation/bloc/tv_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/core.dart' as _i2;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tvseries/domain/usecases/tv_series_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvRepository_0 extends _i1.SmartFake implements _i2.TvRepository {
  _FakeTvRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesUseCase extends _i1.Mock implements _i4.TvSeriesUseCase {
  MockTvSeriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getOnAiringTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnAiringTv,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #getOnAiringTv,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getPopularTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTv,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #getPopularTv,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getTopRatedTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTv,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #getTopRatedTv,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.TvSeriesDetail>> getTvDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, _i2.TvSeriesDetail>>.value(
                _FakeEither_1<_i2.Failure, _i2.TvSeriesDetail>(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, _i2.TvSeriesDetail>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #getTvRecommendations,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> searchTv(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #searchTv,
            [query],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>.value(
                _FakeEither_1<_i2.Failure, List<_i2.TvSeries>>(
          this,
          Invocation.method(
            #getWatchlistTv,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TvSeries>>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> saveWatchlistTv(
          _i2.TvSeriesDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistTv,
          [tv],
        ),
        returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
            _FakeEither_1<_i2.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistTv,
            [tv],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> removeWatchlistTv(
          _i2.TvSeriesDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTv,
          [tv],
        ),
        returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
            _FakeEither_1<_i2.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistTv,
            [tv],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i2.Failure, String>>);
  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
